---
apiVersion: batch/v1
kind: Job
metadata:
  name: phase-two-sleep-7
  labels:
    app: phase-two-sleep-7
spec:
  template:
    metadata:
      name: phase-two-sleep-7
      labels:
        app: phase-two-sleep-7
    spec:
      restartPolicy: Never
      containers:
      - name: phase-two-sleep-7
        image: alpine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          sleep 7
