---
apiVersion: batch/v1
kind: Job
metadata:
  name: phase-two-sleep-10
  labels:
    app: phase-two-sleep-10
spec:
  template:
    metadata:
      name: phase-two-sleep-10
      labels:
        app: phase-two-sleep-10
    spec:
      restartPolicy: Never
      containers:
      - name: phase-two-sleep-10
        image: alpine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          sleep 10
