apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: jobernetes
subjects:
- kind: ServiceAccount
  name: jobernetes
roleRef:
  kind: ClusterRole
  name: jobernetes
  apiGroup: rbac.authorization.k8s.io
